language: c

matrix:
  include:
  - os: linux
    compiler: gcc
    env: SDL_LIB=SDL2-2.0.9 SDL_MIXER_LIB=SDL2_mixer-2.0.4 RUN_CODECOV=1
  - os: linux
    compiler: gcc
    env: SDL_LIB=SDL2-2.0.0 SDL_MIXER_LIB=SDL2_mixer-2.0.0
  - os: linux
    compiler: clang
    env: SDL_LIB=SDL2-2.0.9 SDL_MIXER_LIB=SDL2_mixer-2.0.4
  - os: osx
    compiler: clang
    env: SDL_LIB=SDL2-2.0.9 SDL_MIXER_LIB=SDL2_mixer-2.0.4
  - os: linux
    name: PS Vita
    env: VITA_BUILD=true
    services:
      - docker

install:
  - if [ $VITA_BUILD = true ];
    then
      docker create --name vitasdk -v "${TRAVIS_BUILD_DIR}:/build/git" gnuton/vitasdk-docker
    fi

cache:
  directories:
  - $SDL_LIB
  - $SDL_MIXER_LIB

before_install:
  - function install_sdl_lib {
      if [ -d $1/build ];
      then
        cp -r $1 $1-final;
        cd $1-final/build;
      else
        if [[ $1 == SDL2-* ]];
        then
          SDL_LIB_URL=https://www.libsdl.org/release/$1.tar.gz;
        else
          SDL_LIB_URL=${1#*_};
          SDL_LIB_URL=${SDL_LIB_URL%-*};
          SDL_LIB_URL=https://www.libsdl.org/projects/SDL_$SDL_LIB_URL/release/$1.tar.gz;
        fi;
        travis_retry curl -L $SDL_LIB_URL | tar xz;
        cd $1;
        mkdir build;
        cd build;
        ../configure;
      fi;
      make;
      sudo make install;
      cd ../..;
      }
  - if [ ! $VITA_BUILD = true ];
    then
      install_sdl_lib $SDL_LIB
      install_sdl_lib $SDL_MIXER_LIB
    fi;

before_script:
  - if [ ! $VITA_BUILD = true ];
    then
      mkdir build && cd build && cmake ..
    else
      docker exec -v "${TRAVIS_BUILD_DIR}:/build/git" vitasdk /bin/bash -c "mkdir build && cd build && cmake -DVITA_BUILD=ON .."
    fi;

script:
  - if [ ! $VITA_BUILD = true ];
    then
      make
      make test
    else
      docker exec -v "${TRAVIS_BUILD_DIR}:/build/git" vitasdk /bin/bash -c "make"
    fi;

after_success:
  - if [ $RUN_CODECOV ];
    then
      bash <(curl -s https://codecov.io/bash);
    fi;
