language: c

matrix:
  # Note: If you add a build here or change the order, you need to update the CI badges in README.md as well!
  include:
  - os: linux
    compiler: gcc
    env: SDL_LIB=SDL2-2.0.9 SDL_MIXER_LIB=SDL2_mixer-2.0.4 RUN_CODECOV=1
  - os: linux
    compiler: gcc
    env: SDL_LIB=SDL2-2.0.0 SDL_MIXER_LIB=SDL2_mixer-2.0.0
  - os: linux
    compiler: clang
    env: SDL_LIB=SDL2-2.0.9 SDL_MIXER_LIB=SDL2_mixer-2.0.4
  - os: osx
    compiler: clang
    env: SDL_LIB=SDL2-2.0.9 SDL_MIXER_LIB=SDL2_mixer-2.0.4
  - os: linux
    name: PS Vita
    env: VITA_BUILD=true DEPLOY=vita
    services:
      - docker
  - os: linux
    name: Nintendo Switch
    env: SWITCH_BUILD=true DEPLOY=switch

before_deploy:
  - bash ./.ci_scripts/bintray_conf.sh

deploy:
  provider: bintray
  on:
    all_branches: true
    repo: devnoname120/julius
    condition: $DEPLOY
  file: bintray.json
  user: devnoname120
  skip-cleanup: true
  key:
    secure: "pa8CJAszp4A3d/8BBygqj4h9OMMrxOiDyiO/0zGaJTTvHSd3exAcZpPg5iSPcedADq1usr0sB3XSpmlCmf4PzjOlHG7zVJOXc/GA5QOFEeleE3nntQXQteJbNng2QGYJyiLkY56zsIPns4QYTjqExuNi4AG2oUK5XukY7iP7g+qlCe4W5gepnCUjjEC30aqAiF9gOud4cwmER8h/uNdyiIP/wdQxutl3lVTb7D7DTzKAjBkVEMlGW0vHEY5yMpM5aA5VPAapFD7OjIHA94iD43Iqe1S3PyjLAjIHRE6gLkV4C/s23DoXc8TwINbqCwfVXUsad8iOyRrWG+L4IqPRJomLCzFg0BfZ4AvhVEj3KxA3ONHxSAW5LRBiy47HxKpA/mEZ1SJY3sGnn96isrc+r2O0IWIuiyeGE7cacbvUTXqnMDuryogI5pzwzxJ1OJZH+dM9w7xedTGzlWWzyBH3pBFjSR+B+DRWgoHhz+rRswSysHmstKQDdf0GfO0Mi2uR0CYY1hJwTh4OQ2GXgGgad/fHak2H6ujrp04y7EInkQn5JnV6tj1oVfPvAYk1YxFj3J4sagVaASynDQgTknTjlyOJ6zFVq0v401uSjVRv0e89urJCUiz1YnMhSwKDpn9AWUVlEgtLWhDIyiSOKNVhoCfT7loc/eHHd1DYDip56C0="

install:
  - ./.ci_scripts/docker.sh
cache:
  directories:
  - $SDL_LIB
  - $SDL_MIXER_LIB

before_install:
  - ./.ci_scripts/setup.sh

before_script:
  - ./.ci_scripts/setup_dir.sh

script:
  - ./.ci_scripts/run.sh

after_success:
  - if [ $RUN_CODECOV ];
    then
      bash <(curl -s https://codecov.io/bash);
    fi;
