language: c
compiler: gcc
sudo: require
dist: xenial # Oldest still-supported LTS right now against which the AppImage is built. Update this to the next LTS when support drops.

matrix:
  # Note: If you add a build here or change the order, you need to update the CI badges in README.md as well!
  include:
  - os: linux
    compiler: gcc
    env: SDL_LIB=SDL2-2.0.9 SDL_MIXER_LIB=SDL2_mixer-2.0.4 RUN_CODECOV=1
  - os: linux
    compiler: gcc
    env: SDL_LIB=SDL2-2.0.0 SDL_MIXER_LIB=SDL2_mixer-2.0.0
  - os: linux
    compiler: clang
    env: SDL_LIB=SDL2-2.0.9 SDL_MIXER_LIB=SDL2_mixer-2.0.4
  - os: linux
    name: Linux AppImage
    compiler: gcc
    env: SDL_LIB=SDL2-2.0.9 SDL_MIXER_LIB=SDL2_mixer-2.0.4 BUILD_TARGET=appimage DEPLOY=appimage
    services:
      - docker
  - os: osx
    compiler: clang
    env: SDL_LIB=SDL2-2.0.9 SDL_MIXER_LIB=SDL2_mixer-2.0.4 BUILD_TARGET=mac DEPLOY=mac
  - os: linux
    name: PS Vita
    env: BUILD_TARGET=vita DEPLOY=vita
    services:
      - docker
  - os: linux
    name: Nintendo Switch
    env: BUILD_TARGET=switch DEPLOY=switch

cache:
  directories:
  - $SDL_LIB
  - $SDL_MIXER_LIB

install:
  - ./.ci_scripts/start_docker.sh
  - if [ "$BUILD_TARGET" != "appimage" ];
    then
      ./.ci_scripts/install_sdl.sh;
    else
      sudo apt-get -y install libgl1-mesa-dev libsdl2-dev libsdl2-mixer-dev;
    fi;

before_script:
  - ./.ci_scripts/run_cmake.sh

script:
  - ./.ci_scripts/run_build.sh
  - if [ "$BUILD_TARGET" == "appimage" ];
    then
      ./.ci_scripts/package_appimage.sh;
    fi;

after_success:
  - if [ $RUN_CODECOV ];
    then
      bash <(curl -s https://codecov.io/bash);
    fi;

before_deploy:
  - ./.ci_scripts/bintray_conf.sh

deploy:
  provider: bintray
  on:
    all_branches: true
    repo: devnoname120/julius
    condition: $DEPLOY
  file: bintray.json
  user: devnoname120
  skip_cleanup: true
  key:
    secure: F4CpsUa+h2vty6RlyqYd47f4IPLfHEKdFMaWbpWDhBvM8aJLm2MsycWepIs7SUDnUJANJaSxeqwu2wSIS4Mt34sYlBeWs9SBAYkzubXiE8ewL5OJmajCEVsbhoJ3jozzcTHSYie0xz97i9WRs/my/A1pKr6SfelhsH/JLzqPlEcCq6kol/h5wvUflekAi9zMofELnGHQgtGKgtt6euAP7UpmTXDkYxWq1hQZ6JKyRR+H5LhfVXS6x+UnDySytgjZAnoIJoWgFwFrRCIWp+UXVBOb8RNDaXL4U4HOF70AlArWO5tsLWM7riyjeNlChPOqADzmYEMw/AWpkLYaRSsB3VYQlQnc3lIFjtkz8fC38mfO2rA1wb4VGDEocuvM4cQIzbCf9Pcs40S5hfCkP6ptpSUsJ62kzjHHsQhBryrbOrk7GEyYG8jja/UKyhIjF0i0XelqKm7bukfHvXMAYiAazZBfOBhA8n1bXeOC6ISSD+y9akiCcyRuplxutQFNHzy4gJm+oOkwT3Z+Z6rILH56VzSgs8o2OPHftubwzg4u7LRwVFPRyn6RNOYwZFyJN/YxDZsS4P02L5ZAKY6YmyQjIpiunigEx2KbhYsRcheVED4sP1WLJp/OmPDQ8TMtsutj3o73++BGoqNvvfa6UdOJ2hrZTLTY/0DZ9SYWeqMJaYs=

after_deploy:
  - ./.ci_scripts/bintray_link.sh
